---
name: On-push

on:
  push

jobs:
  run-workflow-empty:
    uses: ./.github/workflows/wf.yaml
  run-workflow-blank:
    uses: ./.github/workflows/wf.yaml
    with:
      PBS: ""
  run-workflow-filled:
    uses: ./.github/workflows/wf.yaml
    with:
      PBS: "path/to/script.sh"
