---
name: Test workflow

on:
  workflow_call:
    inputs:
      PBS:
        description: >
          List of envs to run. These MUST be passed as a string representing
          a list of strings, e.g.:

          '["lint", "build"]'
        required: false
        default: ""
        type: string

jobs:
  process-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ${{ fromJSON(inputs.PBS) }}

    steps:
      - uses: actions/checkout@v4
      - name: Echo stuff
        run: |
          echo "${{ matrix.version }}"
  # run-gha:
  #   name: Run my test action
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: test-if
  #       if: ${{ hashFiles(inputs.PBS) }}
  #       run: |
  #         echo "The input ${{ inputs.PBS }} was true"
  #     - name: test-if-not
  #       if: ${{ !hashFiles(inputs.PBS) }}
  #       run: |
  #         echo "The inverse of input ${{ inputs.PBS }} was true"
